---
controller_execution_environments:
  - name: "Ansible Lint EE"
    description: "For performing ansible-lint testing"
    organization: "Default"
    image: "quay.io/ansible/creator-ee:latest"
    pull: "missing"
  - name: "Minimal execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest"
    pull: "missing"
  - name: "Ansible Engine 2.9 execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-23/ee-29-rhel8:latest"
    pull: "missing"
  - name: "Default execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest"
    pull: "missing"
  - name: "Control Plane Execution Environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest"
    pull: "missing"
...
