---
controller_settings:
  - settings:
      LICENSE:
        instance_count: 16
        license_date: 1720929599
        license_type: enterprise
        pool_id: 2c94cdce890c6dae01895837e7081b6b
        product_name: Red Hat Ansible Automation Platform
        satellite: null
        sku: RH00798
        subscription_name: Red Hat Developer Subscription for Individuals
        support_level: Self-Support
        valid_key: true
      SUBSCRIPTIONS_USERNAME: "pchandna"
      SUBSCRIPTIONS_PASSWORD: "$encrypted$"
      INSTALL_UUID: "8a76d2a6-d6a3-479f-a512-a8f4f34ad692"
      INSIGHTS_TRACKING_STATE: "false"
      PENDO_TRACKING_STATE: "off"
      AUTH_LDAP_SERVER_URI: ""
      AUTH_LDAP_BIND_DN: ""
      AUTH_LDAP_BIND_PASSWORD: ""
      AUTH_LDAP_START_TLS: "false"
      AUTH_LDAP_CONNECTION_OPTIONS:
        OPT_NETWORK_TIMEOUT: 30
        OPT_REFERRALS: 0
      AUTH_LDAP_USER_SEARCH:
        []
      AUTH_LDAP_USER_DN_TEMPLATE: "null"
      AUTH_LDAP_USER_ATTR_MAP:
        {}
      AUTH_LDAP_GROUP_SEARCH:
        []
      AUTH_LDAP_GROUP_TYPE: "MemberDNGroupType"
      AUTH_LDAP_GROUP_TYPE_PARAMS:
        member_attr: member
        name_attr: cn
      AUTH_LDAP_REQUIRE_GROUP: "null"
      AUTH_LDAP_DENY_GROUP: "null"
      AUTH_LDAP_USER_FLAGS_BY_GROUP:
        {}
      AUTH_LDAP_ORGANIZATION_MAP:
        {}
      AUTH_LDAP_TEAM_MAP:
        {}
...
